[project]
name = "flaskr"
version = "1.0.0"
description = "The basic user authentication app"
dependencies = [
    "flask","sqlalchemy","faker"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"